const data = [
  { title: 'My Aim is True', year: '1977' },
    { title: "This Year's Model", year: '1978' },
    { title: 'Armed Forces', year: '1979' },
    { title: 'Get Happy', year: '1980' },
    { title: 'Trust', year: '1981' },
    { title: 'Almost Blue', year: '1981' },
    { title: 'Imperial Bedroom', year: '1982'},
    { title: 'Punch the Clock', year: '1983' },
    { title: 'Goodbye Cruel World', year: '1984'},
    { title: 'King of America', year: '1986' },
    { title: 'Blood and Chocolate', year: '1986' },
    { title: 'Spike', year: '1989' },
    { title: 'Mighty Like a Rose', year: '1991' },
    { title: 'The Juliette Letters', year: '1993' },
    { title: 'Brutal Youth', year: '1994' },
    { title: 'Kojak Variety', year: '1995' },
    { title: 'All This Useless Beauty', year: '1996' },
    { title: 'Painted from Memory', year: '1998' },
    { title: 'When I Was Cruel', year: '2002' },
    { title: 'North', year: '2003' },
    { title: 'The Delivery Man', year: '2004' },
    { title: 'The River in Reverse', year: '2006' },
    { title: 'Momofuku', year: '2008'},
    { title: 'Secret, Profane & Sugarcane', year: '2009' },
    { title: 'National Ransom', year: '2009' },
    { title: 'Wise Up Ghost', year: '2013' }
];

export default data;